# Generated by Django 5.1.7 on 2025-05-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
