# Generated by Django 5.1.7 on 2025-04-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(default='>>> http://localhost:9001/browser/web/images.jfif'),
            preserve_default=False,
        ),
    ]
