# Generated by Django 5.1.7 on 2025-05-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('formatted', 'Оформлена'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], default='draft', max_length=20),
        ),
    ]
